version: 3

services:
	postgres:
		image: "postgres"
		ports:
			- "5432:5432"
      environment:
         POSTGRES_USER: root
         POSTGRES_PASSWORD: root
         POSTGRES_DB: chitragupta
   api:
      build: ./api
      expose:
         - 5000
      ports:
         - "5000:5000"
      volumes:
         - ./api:/usr/src/app
		depends_on:
			- postgres
		environment:
         WAIT_HOSTS: postgres:5432
         WAIT_BEFORE_HOSTS: 10
   app:
      build: ./app
      expose:
         - 3000
      ports:
         - "3000:3000"
      volumes:
         - ./app:/usr/src/app
		depends_on:
			- api
