version: "3.5"

services:
    db:
        image: postgres
        container_name: postgres
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=chitragupta
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root

    server:
        container_name: server
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "5000:5001"
        volumes:
            - ./server:/usr/src/app
        depends_on:
            - "db"
        environment:
            WAIT_HOSTS: postgres:5432
            WAIT_BEFORE_HOSTS: 5

    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - "./client:/usr/src/app"
            - "/usr/src/app/node_modules"
        ports:
            - "3000:3000"
        depends_on:
            - "server"
